export const tshirts = [
  {
    id: "0",
    photos: ["/camiseta1.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "1",
    photos: ["/camiseta2.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "2",
    photos: ["/camiseta3.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "boné muito louco",
  },
  {
    id: "3",
    photos: ["/camiseta4.webp"],
    name: "camiseta",
    price: 149.9,
    category: "camiseta",
    description: "calça maneira",
  },
  {
    id: "4",
    photos: ["/camiseta5.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "5",
    photos: ["/camiseta6.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "6",
    photos: ["/camiseta7.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "7",
    photos: ["/camiseta8.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "8",
    photos: ["/camiseta9.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "9",
    photos: ["/camiseta10.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "10",
    photos: ["/camiseta11.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "11",
    photos: ["/camiseta12.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "12",
    photos: ["/camiseta13.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "13",
    photos: ["/camiseta14.webp"],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
];

export const caps = [
  {
    id: "14",
    photos: ["/bone0.webp"],
    name: "bone",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
  {
    id: "15",
    photos: ["/bone9.webp"],
    name: "bone",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
  {
    id: "16",
    photos: ["/bone2.webp"],
    name: "bone",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
  {
    id: "17",
    photos: ["/bone3.webp"],
    name: "bone",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
  {
    id: "18",
    photos: ["/bone4.webp"],
    name: "bone",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
  {
    id: "19",
    photos: ["/bone5.webp"],
    name: "camiseta",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
  {
    id: "20",
    photos: ["/bone6.webp"],
    name: "bone",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
  {
    id: "21",
    photos: ["/bone7.webp"],
    name: "bone",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
  {
    id: "22",
    photos: ["/bone8.webp"],
    name: "bone",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
  {
    id: "23",
    photos: ["/bone9.webp"],
    name: "bone",
    price: 49.9,
    category: "bone",
    description: "camiseta ecko descolada",
  },
];

export const products = [...tshirts, ...caps];
