export const products = [
  {
    id: "0",
    photos: [],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "1",
    photos: [],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "2",
    photos: [],
    name: "boné",
    price: 49.9,
    category: "bones",
    description: "boné muito louco",
  },
  {
    id: "3",
    photos: [],
    name: "calça",
    price: 149.9,
    category: "calca",
    description: "calça maneira",
  },
  {
    id: "4",
    photos: [],
    name: "relogio",
    price: 49.9,
    category: "acessorio",
    description: "camiseta ecko descolada",
  },
  {
    id: "5",
    photos: [],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
  {
    id: "6",
    photos: [],
    name: "camiseta",
    price: 49.9,
    category: "camiseta",
    description: "camiseta ecko descolada",
  },
];
