import StyledComponentsRegistry from "./lib/registry";
import { Inter } from "next/font/google";
// import { GlobalStyle } from "@/global/styles";
import { Providers } from "./providers";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import { TCategory, TProduct } from "@/interfaces";
import { TSeller } from "@/interfaces/seller";
import { api } from "@/services/api";

export const metadata = {
  title: "Layover Skateshop",

  description: "Generated by Next.js",
};

const inter = Inter({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data: {
    seller: TSeller;
    categories: TCategory[];
    products: TProduct[];
  } = (await api.get("/sellers/products")).data;

  const { seller, categories, products } = data;

  return (
    <html lang="pt-BR" className={inter.className}>
      <body>
        <Providers>
          <Header products={products} categories={categories} />
          <Navbar products={products} categories={categories} />

          {children}
        </Providers>
      </body>
    </html>
  );
}
